package com.mycompany.codicefiscale;

import java.io.File;
import java.util.Scanner;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;


public final class App extends javax.swing.JFrame {


    String ggs[] = {"","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"};
    String mms[] = {"","1","2","3","4","5","6","7","8","9","10","11","12"};
    
    final char vocali[] = {'a','e','i','o','u'};
    final char consonanti [] = {'b', 'c', 'd','f','g','h','j','k','l','m','n','p','q','r','s','t','v','w','x','y','z'};    
    
    int listaAnni[] = new int[122];
    String anni[] = new String[123];
    
    
    public App() {
        initComponents();
        conf();
    }

    public void conf() {
        listaAnni[0]=2021;
        
        for (int i=1; i<122; i++)
        {
            listaAnni[i]=(listaAnni[i-1])-1;
        }
         
        anni[0]="";
        jComboBox3.addItem(anni[0]);
        
        for (int i = 1; i < 123; i++) {
            anni[i] = String.valueOf(listaAnni[i-1]);
            jComboBox3.addItem(anni[i]); // Aggiugiamo gli elementi del vettore nella ComboBox
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>(mms);
        jComboBox2 = new javax.swing.JComboBox<String>(ggs);
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();

        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Codice Fiscale");
        setResizable(false);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Maschio");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Femmina");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Cognome");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Luogo di nascita");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Provincia di nascita (sigla)");

        jTextField5.setToolTipText("Massimo 2 lettere");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Data di nascita");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<String>(mms));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<String>(ggs));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>());
        jComboBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jComboBox3.setName(""); // NOI18N
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Codice fiscale");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Sesso");

        jLabel8.setText("Giorno");

        jLabel9.setText("Mese");

        jLabel10.setText("Anno");

        jButton1.setText("Calcola");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancella");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 36)); // NOI18N
        jLabel11.setText("Codice Fiscale");
        jLabel11.setToolTipText("Clicca per le informazioni");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setToolTipText("Premi CTRL+C per copiare il codice");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Visualizza errori");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField4)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel9)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel10))
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3))
                                        .addGap(67, 67, 67))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField3)
                                            .addComponent(jTextField1))
                                        .addGap(14, 14, 14)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(105, 105, 105))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        char nome[] = new char[100];
        char cognome[] = new char[100];
        int gg=0, mm=0, sesso=2, cc=0;
        String anno="", luogo="", prov="", cf="", textCognome = "";
        boolean vcf;
        
        char vDispari [] = {'0', '1', '2', '3', '4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'};
        int pDispari [] = {1,0,5,7,9,13,15,17,19,21,1,0,5,7,9,13,15,17,19,21,2,4,18,20,11,3,6,8,12,14,16,10,22,25,24,23};
        char vPari [] = {'0', '1', '2', '3', '4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'};
        int pPari [] = {0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25};
        
        char restoVal [] = {'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'};
        int cv=0;
        
        try{
            String nome1 = jTextField1.getText();
            nome1 = nome1.toLowerCase();
            
            String textNome="";
           // textNome = textNome.toLowerCase();
            
            for(int i=0; i<nome1.length();i++){    
              if (nome1.charAt(i)!=' ') {
                  textNome = textNome+nome1.charAt(i);
              }
            }

            for (int i=0; i<textNome.length(); i++) {
                nome[i] = textNome.charAt(i);
            }
            vcf = !textNome.equals("") && textNome.matches("^[a-zA-Z]+$"); // Regex solo lettere

            if (vcf==true){
                textCognome = jTextField2.getText();
                textCognome=textCognome.toLowerCase();
                for (int i=0; i<textCognome.length(); i++) {
                    cognome[i] = textCognome.charAt(i);
                }   
                luogo = jTextField3.getText();
                luogo = luogo.toLowerCase();
                prov = jTextField5.getText();
                prov = prov.toLowerCase();
                vcf = !luogo.equals(""); // formula 
                int a=jComboBox2.getSelectedIndex();
                int b=jComboBox1.getSelectedIndex();
                int c=jComboBox3.getSelectedIndex();
                if ("".equals(ggs[a]) || "".equals(mms[b]) || "".equals(anni[c])) {
                    vcf=false;
                }
                else {
                    gg=Integer.parseInt(ggs[a]);
                    mm=Integer.parseInt(mms[b]);
                    anno=anni[c];
                }
            }

        if (vcf==true) {
            if (jRadioButton1.isSelected())
            {
                sesso=0;
                vcf=true;
            }
            else if (jRadioButton2.isSelected()) {
                sesso=1;
                vcf=true;
            }
            else {
                vcf=false;
            }
           }


            if (vcf==true){
                if (textCognome.length()<3) {
                    cf=textCognome+"X";
                }
                else {
                    for (int i=0; i<textCognome.length(); i++) 
                    {
                        for (int z=0; z<21; z++)
                        {
                            if (cognome[i]==consonanti[z]) 
                            {
                                cc=cc+1;
                                if (cc<=3) 
                                {
                                    cf=cf+cognome[i];
                                }
                            }
                        }
                    }
                    if (cc<3)
                    {
                        for (int i=0; i<textCognome.length(); i++)
                        {
                            for (int z=0; z<5; z++)
                            {
                            if (cognome[i]==vocali[z])  {
                                cc=cc+1;
                                if (cc<=3) {
                                    cf=cf+cognome[i];
                                }
                            }
                        }  
                    }
                }
           }



                cc=0;
                char vettCont[] = new char[100];
                if (textNome.length()<3)
                {
                    cf=cf+textNome;
                    cf=cf+"X";
                }
                else {
                    for (int i=0; i<textNome.length(); i++) {
                        for (int z=0; z<21; z++) {
                            if (nome[i]==consonanti[z])
                            {
                                vettCont[cc]=nome[i];
                                cc=cc+1;
                            }
                        }
                    }

                    if (cc==3) {
                        cf=cf+vettCont[0]+vettCont[1]+vettCont[2];
                    }
                    else if (cc>=4) {
                        cf=cf+vettCont[0]+vettCont[2]+vettCont[3];
                    }

                    else if (cc<3)
                    {
                        switch (cc) {
                            case 1:
                                cf=cf+vettCont[0];
                                for (int i=0; i<textNome.length(); i++) {
                                    for (int z=0; z<5; z++)
                                    {
                                        if (cv<2) {
                                            if (nome[i]==vocali[z])
                                                {
                                                 cv=cv+1;
                                                 cf=cf+nome[i];
                                                }
                                            }
                                        }
                                    }
                            break;

                            case 2:
                                cf=cf+vettCont[0]+vettCont[1];
                                for (int i=0; i<textNome.length(); i++)
                                {
                                    for (int z=0; z<5; z++)
                                    {
                                       if (cv<1) {


                                        if (nome[i]==vocali[z])
                                        {
                                            cv=cv+1;
                                            cf=cf+nome[i];
                                        }
                                    }
                                       }
                                }
                               break;
                        }

                    }
                }

                char[] codiceAnno = anno.toCharArray();
                cf = cf + codiceAnno[2] + codiceAnno[3];
                switch (mm) {
                     case 1:
                    cf = cf+'A';
                    break;
                case 2:
                    cf = cf+'B';
                    break;
                case 3:
                    cf = cf+'C';
                    break;
                case 4:
                    cf = cf+'D';
                    break;
                case 5:
                    cf = cf+'E';
                    break;
                case 6:
                    cf = cf+'H';
                    break;
                case 7:
                    cf = cf+'L';
                    break;
                case 8:
                    cf = cf+'M';
                    break;
                case 9:
                    cf = cf+'P';
                    break;
                case 10:
                    cf = cf+'R';
                    break;
                 case 11:
                    cf = cf+'S';
                    break;
                case 12:
                    cf = cf+'T';
                    break;
                    }

                if (gg>=1 && gg<=9) {
                    if (sesso==0) {
                        cf = cf + ("0"+gg+"");
                    }
                    else if (sesso==1){
                        cf = cf + ((gg+40)+"");
                    }
                }
                else {
                    if (sesso==0) {
                        cf = cf +(gg+"");
                    }
                    else if (sesso==1){
                        cf = cf + ((gg+40)+"");
                    }
                }

               File inputFile = new File("comuni.txt");
               Scanner scannerDaFile = new Scanner (inputFile);

               boolean trovato = false;
               String frase;
               StringTokenizer parola = null;
               String provConfronto="", id="";
               String luogoConfronto="";
               try {
                    do {
                    for (int i=0; i<10; i++) {
                    switch (i) {
                        case 0: 
                        {
                            while(scannerDaFile.hasNextLine()) {
                                frase=scannerDaFile.nextLine();
                                parola = new StringTokenizer(frase, " ");
                                id = parola.nextToken();
                                break;
                            } 
                        }
                        break;

                       case 1:
                           provConfronto = parola.nextToken();
                           break;

                       case 2:
                       {
                           luogoConfronto = parola.nextToken();
                           if (parola.hasMoreTokens()) {
                               while (parola.hasMoreTokens()) {
                                   luogoConfronto = luogoConfronto + " "+ parola.nextToken();
                               }
                           }  
                           if (provConfronto.equalsIgnoreCase(prov)) {
                               if (luogoConfronto.equalsIgnoreCase(luogo)) {
                                   trovato=true;
                               }       }
                           }
                       break;
                        }
                    }
                }
                   while (trovato==false);

                   if (trovato==true) {
                       if (provConfronto.equalsIgnoreCase(prov)) {
                       if (luogoConfronto.equalsIgnoreCase(luogo)) {
                           cf = cf + id;
                       } 
                   }
               }
            }
               catch (Exception e) {
                   JOptionPane.showMessageDialog(null, "Città non trovata nel file comuni.txt", "Errore luogo", JOptionPane.ERROR_MESSAGE);
                }

               final int lungCodice = 16;
               final int lungAlfaChars = 36;
               char[] cff= new char[lungCodice];

               cff[0]=' ';
               for (int i = 1; i < lungCodice; i++) {
                    cff[i] = cf.charAt(i-1);
                    
            }

          int nPari = 0, nDispari=0;

          for (int i=1; i<lungCodice; i++) 
          {
              cff[i] = Character.toUpperCase(cff[i]);
          }

          for (int i=1; i<lungCodice; i++) {
               for (int a=0; a<lungAlfaChars; a++) {
                    if (i%2==0)
                    {
                        if (cff[i] == vPari[a]) {
                           nPari = nPari + pPari[a]; 
                        }
                    }

                    else if (i%2!=0) {
                        if (cff[i]==vDispari[a]){
                           nDispari = nDispari + pDispari[a]; 
                        }
                    }
               }
           }



            float resto = (nPari+nDispari)%26;
           // resto = resto%26;
            char restoLett=' ';
            for (int i=0; i<25; i++) {
                if (resto==i) {
                    restoLett=restoVal[i];
                }
            }

            cf=cf+restoLett;
            cf=cf.toUpperCase(); // Aggiorna tutto in maiuscolo
            jTextField4.setText(cf);
            
            }
            else { // Else del try
                JOptionPane.showMessageDialog(null, "Inserisci correttamente i valori", "Errore", JOptionPane.ERROR_MESSAGE);
            }
            }       
            catch (Exception e) {
                if(jCheckBox1.isSelected()) {
                    JOptionPane.showMessageDialog(null, e, "Errore", JOptionPane.ERROR_MESSAGE);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Inserisci correttamente i valori", "Errore", JOptionPane.ERROR_MESSAGE);
                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jComboBox2.setSelectedIndex(0);
        jComboBox1.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
         JOptionPane.showMessageDialog(null, "Programma scritto da Simone Campisi, Elio Magnano, Steven Vinci & Zaffarana Carmelo.\n4B Informatica, 2021", "Devs", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
